# Generated by Django 4.2.3 on 2023-09-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Live events', 'Live events'), ('Corporate workshops', 'Corporate workshops'), ('Past events', 'Past events')], default=None, max_length=50)),
                ('description', models.TextField(default=None, max_length=800)),
                ('event_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
