# Generated by Django 4.2.3 on 2023-08-25 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewChapterApplication',
            fields=[
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied at')),
                ('institution_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=100, null=True, verbose_name='Last Name')),
                ('year', models.IntegerField()),
                ('define_sdg', models.TextField(max_length=250)),
                ('shown_leadership', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('leadership_experience', models.TextField(max_length=800)),
                ('community_service', models.TextField(max_length=550)),
                ('reason_for_chapter', models.TextField(max_length=600)),
                ('chapter_recognition', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], default='Y', max_length=5)),
                ('plans_for_chapter', models.TextField(max_length=800)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('hours', models.CharField(max_length=100)),
                ('queries', models.CharField(max_length=800)),
                ('selected', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
