# Generated by Django 4.2.3 on 2023-08-28 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0002_remove_newchapterapplication_community_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=220)),
                ('total_members', models.IntegerField(default=0)),
                ('established_on', models.DateField(auto_now_add=True, verbose_name='Chapter Estd. On')),
                ('chapter_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
