# Generated by Django 4.2.3 on 2023-08-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_joinchapterapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinchapterapplication',
            name='institution_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.newchapterapplication'),
        ),
    ]
