# Generated by Django 4.2.3 on 2023-09-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_alter_joinchapterapplication_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinchapterapplication',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joinchapterapplication',
            name='is_volunteer',
            field=models.BooleanField(default=True),
        ),
    ]
