# Generated by Django 4.2.3 on 2023-09-09 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied at')),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default=None, max_length=49)),
                ('city', models.CharField(default=None, max_length=100)),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=100, null=True, verbose_name='Last Name')),
                ('committed', models.TextField(max_length=250)),
                ('introduction', models.TextField(default=None, max_length=250)),
                ('experience', models.TextField(default=None, max_length=800)),
                ('expertise', models.TextField(default=None, max_length=800)),
                ('reasons_for_chapter', models.TextField(max_length=600)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('selected', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
