# Generated by Django 4.2.3 on 2023-09-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_alter_joinapplication_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinapplication',
            name='send_email',
        ),
        migrations.RemoveField(
            model_name='joinchapterapplication',
            name='send_email',
        ),
        migrations.RemoveField(
            model_name='newchapterapplication',
            name='send_email',
        ),
    ]
