# Generated by Django 4.2.3 on 2023-09-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='num_counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trees', models.IntegerField(default=0)),
                ('beaches', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('plastic', models.IntegerField(default=0)),
            ],
        ),
    ]
