# Generated by Django 4.2.3 on 2023-09-09 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_what_we_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='what_we_do',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
