# Generated by Django 4.2.3 on 2023-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_what_we_do_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='num_counts',
            name='beaches',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='num_counts',
            name='plastic',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='num_counts',
            name='projects',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='num_counts',
            name='trees',
            field=models.IntegerField(default=157),
        ),
    ]
