# Generated by Django 4.2.3 on 2023-09-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle', models.BooleanField(default=False)),
                ('car', models.BooleanField(default=False)),
                ('bus', models.BooleanField(default=False)),
                ('train', models.BooleanField(default=False)),
                ('plane', models.BooleanField(default=False)),
                ('ship', models.BooleanField(default=False)),
                ('q_motorcycle', models.PositiveIntegerField(default=0)),
                ('persons_motorcycle', models.PositiveIntegerField(default=0)),
                ('total_carbon_footprint', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
