# Generated by Django 4.2.3 on 2023-09-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonfp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonfootprint',
            name='total_carbon_footprint',
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='persons_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='q_bus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='q_car',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='q_plane',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='q_ship',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='q_train',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='persons_motorcycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='q_motorcycle',
            field=models.FloatField(default=0.0),
        ),
    ]
